openapi: 3.1.0
info:
  title: WeatherService API
  version: 1.0.0
  description: API для работы с данными о погоде
x-ogen:
  target: ./shared/pkg/openapi/study_materials/v1
  package: study_materials_v1
  clean: true

tags:
  - name: Weather
    description: Операции с данными о погоде — получение и обновление информации

paths:
  /api/v1/plan/{plan_id}:
    $ref: ./paths/plan.yaml
