// Code generated by ogen, DO NOT EDIT.

package user_profile_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	GetWeatherByCityOperation    OperationName = "GetWeatherByCity"
	UpdateWeatherByCityOperation OperationName = "UpdateWeatherByCity"
)
