// Code generated by ogen, DO NOT EDIT.

package study_materials_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreatePlanParams is parameters of CreatePlan operation.
type CreatePlanParams struct {
	// Идентификатор плана.
	PlanID int64
}

func unpackCreatePlanParams(packed middleware.Parameters) (params CreatePlanParams) {
	{
		key := middleware.ParameterKey{
			Name: "plan_id",
			In:   "path",
		}
		params.PlanID = packed[key].(int64)
	}
	return params
}

func decodeCreatePlanParams(args [1]string, argsEscaped bool, r *http.Request) (params CreatePlanParams, _ error) {
	// Decode path: plan_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "plan_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.PlanID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
				}).Validate(int64(params.PlanID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "plan_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPlanByIDParams is parameters of GetPlanByID operation.
type GetPlanByIDParams struct {
	// Идентификатор плана.
	PlanID int64
}

func unpackGetPlanByIDParams(packed middleware.Parameters) (params GetPlanByIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "plan_id",
			In:   "path",
		}
		params.PlanID = packed[key].(int64)
	}
	return params
}

func decodeGetPlanByIDParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPlanByIDParams, _ error) {
	// Decode path: plan_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "plan_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.PlanID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
				}).Validate(int64(params.PlanID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "plan_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
