// Code generated by ogen, DO NOT EDIT.

package study_materials_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CreatePlanOperation  OperationName = "CreatePlan"
	GetPlanByIDOperation OperationName = "GetPlanByID"
)
