// Code generated by ogen, DO NOT EDIT.

package study_materials_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreatePlan implements CreatePlan operation.
//
// Создать новый план.
//
// POST /api/v1/plan/{plan_id}
func (UnimplementedHandler) CreatePlan(ctx context.Context, req *CreatePlanRequest, params CreatePlanParams) (r CreatePlanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlanByID implements GetPlanByID operation.
//
// Получить план по идентификатору.
//
// GET /api/v1/plan/{plan_id}
func (UnimplementedHandler) GetPlanByID(ctx context.Context, params GetPlanByIDParams) (r GetPlanByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
